// Controlled browser regression: actual MediaRecorder, packaged decoder and Whisper.
// The microphone stream is injected Web Audio/TTS. This is not a human/mic certification.
import assert from 'node:assert/strict';
import { readFile, cp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { readAloudQuestions } from '../../src/data/question-bank/read-aloud.ts';
import { repeatSentenceQuestions } from '../../src/data/question-bank/repeat-sentence.ts';
import { writeFromDictationQuestions } from '../../src/data/question-bank/write-from-dictation.ts';
import { root, origin, launch, ready, quit, persist } from './common.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
let runtime=launch();await ready(runtime);let installation=root;
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});
const context=await browser.newContext();let page=await context.newPage();const errors=[],outbound=[],mimeTypes=new Set(),cases=[],uploads=[];
async function instrument(p){p.on('pageerror',()=>errors.push('pageerror'));p.on('request',r=>{if(/^https?:/.test(r.url())&&new URL(r.url()).origin!==origin)outbound.push('non-loopback');});await p.addInitScript(()=>{window.cspViolations=[];window.validationUploads=[];const nativeFetch=window.fetch;window.fetch=function(input,options){if(String(input).endsWith('/api/v1/transcribe')&&options?.body instanceof FormData){window.validationUploads.push({keys:[...options.body.keys()].sort(),language:options.body.get('language'),mime:options.body.get('audio')?.type});}return nativeFetch.call(this,input,options);};document.addEventListener('securitypolicyviolation',e=>window.cspViolations.push(e.violatedDirective));});}
await instrument(page);const button=name=>page.getByRole('button',{name,exact:true});const text=name=>page.getByText(name,{exact:true});
async function snapshot(){return page.evaluate(async()=>{const db=await new Promise((res,rej)=>{const r=indexedDB.open('pte-study-db');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});const result={};for(const name of ['attempts','errors','reviews'])result[name]=await new Promise((res,rej)=>{const r=db.transaction(name).objectStore(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});db.close();return result;});}
async function record(fixture,ra,partial=false){
 if(await button('Disable microphone').count())await button('Disable microphone').click();
 await page.route('**/controlled.wav',async r=>r.fulfill({body:await readFile(`tools/local-stt/tmp/controlled/${fixture}.wav`),contentType:'audio/wav'}));
 await page.evaluate(async partial=>{window.controlledContext?.close();const c=new AudioContext();window.controlledContext=c;await c.resume();const buffer=await c.decodeAudioData(await(await fetch('/controlled.wav')).arrayBuffer());const dest=c.createMediaStreamDestination();navigator.mediaDevices.getUserMedia=async()=>dest.stream;window.playControlled=()=>{const src=c.createBufferSource();src.buffer=buffer;src.connect(dest);const done=new Promise(r=>src.onended=r);src.start();if(partial)src.stop(c.currentTime+buffer.duration*.6);return done;};},partial);
 await button('Enable microphone').waitFor();if(ra)await button("I'm ready to read").click();await button('Enable microphone').click();
 if(!ra){await button('Play sentence').click();await button('Replay sentence').waitFor();}
 await button('Start recording').click();await page.evaluate(()=>window.playControlled());await button('Stop recording').click();await text('Your recording is ready.').waitFor();
 await page.evaluate(async()=>{const a=document.querySelector('audio[aria-label="Your recording"]');const done=new Promise((res,rej)=>{const timer=setTimeout(()=>rej(new Error('Playback timeout')),30000);a.onended=()=>{clearTimeout(timer);res();};a.onerror=()=>rej(new Error('Playback failed'));});await a.play();await done;});
 await page.unroute('**/controlled.wav');
}
async function transcribe(){if(await button('Check local runtime').count())await button('Check local runtime').click();await text('Local Whisper transcription ready.').waitFor();const response=page.waitForResponse(r=>r.url().endsWith('/api/v1/transcribe'));await button('Transcribe locally').click();const r=await response;assert.equal(r.status(),200);const metadata=await page.evaluate(()=>window.validationUploads.at(-1));assert.deepEqual(metadata.keys,['audio','language']);assert.equal(metadata.language,'en');mimeTypes.add(metadata.mime);uploads.push({fields:['audio','language'],answerSent:false});await text('Detected speech').waitFor();return r.json();}
function validate(state,before,item,raw,ra){assert.equal(state.attempts.length,before.attempts.length+1);const attempt=state.attempts.find(a=>!before.attempts.some(b=>b.id===a.id));assert.equal(attempt.responseText,raw.text);assert.equal(attempt.itemId,item.id);assert.equal(attempt.metrics.processedLocally,true);assert.equal(attempt.score,attempt.metrics[ra?'textCoverage':'contentRecall']);const e=state.errors.filter(e=>e.attemptId===attempt.id),r=state.reviews.filter(r=>r.sourceAttemptId===attempt.id);assert.equal(e.length,attempt.metrics.totalErrors);assert.equal(r.length,e.length?1:0);for(const error of e){assert.ok(['omission','insertion','substitution'].includes(error.category));assert.equal(error.itemId,item.id);}if(r.length)assert.equal(r[0].answer,item.transcript);if(ra)for(const field of ['responseLatencyMs','endingSilenceMs','speechDurationMs','speechRateWpm'])assert.ok(Number.isFinite(attempt.metrics[field]));else assert.equal(attempt.metrics.totalChunks,item.chunks.length);return {errorRecords:e.length,reviewItems:r.length};}
async function runCase(index,fixture,ra,partial=false){const items=ra?readAloudQuestions:repeatSentenceQuestions;await text(`Question ${index+1} of ${items.length}`).waitFor();const before=await snapshot();await record(fixture,ra,partial);const raw=await transcribe();assert.deepEqual(await snapshot(),before,'Transcription must not save automatically');if(ra){await button('Analyse audio locally').click();await page.getByRole('heading',{name:'Fluency timing'}).waitFor();}await button('Save attempt').click();await text('Attempt saved locally.').waitFor();const impact=validate(await snapshot(),before,items[index],raw,ra);if(partial)assert.ok(impact.errorRecords>0&&impact.reviewItems>0);cases.push({task:ra?'RA':'RS',itemId:items[index].id,controlledPartialUtterance:partial,status:'PASS',...impact});assert.deepEqual(await page.evaluate(()=>window.cspViolations),[]);console.log(JSON.stringify({event:'browser case',task:ra?'RA':'RS',itemId:items[index].id,status:'PASS'}));}
try{
 for(const ra of [true,false]){await page.goto(origin+(ra?'/study/read-aloud':'/study/repeat-sentence'));let current=0;for(const [index,fixture]of ra?[[0,'RA-1'],[2,'RA-M'],[5,'RA-3']]:[[0,'RS-1'],[2,'RS-2'],[4,'RS-3']]){while(current<index){await button(ra?'Next passage':'Next question').click();current++;}await runCase(index,fixture,ra);}}
 await page.goto(origin+'/study/read-aloud');await runCase(0,'RA-1',true,true);
 await page.goto(origin+'/study/write-from-dictation');await button('Play audio').click();await button('Replay audio').waitFor();const beforeWfd=await snapshot();await page.getByLabel('Your answer').fill(writeFromDictationQuestions[0].answer);await button('Submit').click();await text('Attempt saved. Your word-level result is ready.').waitFor();const afterWfd=await snapshot();assert.equal(afterWfd.attempts.length,beforeWfd.attempts.length+1);assert.equal(afterWfd.attempts.find(a=>a.taskType==='write-from-dictation').score,1);await button('Next question').click();assert.equal(await page.getByLabel('Your answer').inputValue(),'');
 const saved=await snapshot();await page.close();page=await context.newPage();await instrument(page);await page.goto(origin);assert.deepEqual(await snapshot(),saved);const second=await context.newPage();await second.goto(origin);assert.equal(new URL(second.url()).origin,origin);await second.close();
 await quit(runtime);runtime=launch();await ready(runtime);await page.reload();assert.deepEqual(await snapshot(),saved);
 const reinstall=join(root,'..','reinstall');await cp(root,reinstall,{recursive:true});await quit(runtime);installation=reinstall;runtime=launch(['--no-browser'],installation);await ready(runtime);await page.reload();assert.deepEqual(await snapshot(),saved);
 assert.deepEqual(errors,[]);assert.deepEqual(outbound,[]);assert.deepEqual(await page.evaluate(()=>window.cspViolations),[]);
 const normalNetworkCount=outbound.length;const csp=await page.evaluate(async()=>{window.cspViolations=[];await fetch('https://example.invalid/csp-probe').catch(()=>{});const script=document.createElement('script');script.src='https://example.invalid/script.js';document.head.append(script);await new Promise(r=>setTimeout(r,300));return window.cspViolations;});console.log(JSON.stringify({event:'CSP challenge',directives:csp}));assert.ok(csp.includes('connect-src')&&csp.some(d=>d.startsWith('script-src')));
 await persist('linux-browser.json',{status:'PASS',browser:{name:'Chrome',version:browser.version(),os:'Linux x64',mediaRecorderMIME:[...mimeTypes],source:'injected Web Audio stream from controlled TTS WAV; actual MediaRecorder and packaged decoding',microphoneAllow:'PENDING',microphoneDeny:'PENDING',microphoneReenable:'PENDING',physicalDevice:'PENDING'},cases,wfd:'PASS',explicitSave:'PASS',noAnswerInRuntimeRequest:'PASS',uploadRequests:uploads.length,persistence:{attempts:saved.attempts.length,errorRecords:saved.errors.length,reviewItems:saved.reviews.length,closeReopenTab:'PASS',runtimeRestart:'PASS',sameVersionReinstallDifferentDirectory:'PASS',stableOrigin:origin,signedVersionUpdate:'PENDING',scope:'same browser profile, same version reinstalled; no study content archived'},normalFlow:{pageErrors:0,cspViolations:0,nonLocalRequests:normalNetworkCount},cspRemoteScriptAndConnect:'PASS',blobPlayback:'PASS',multipleTabs:'PASS',humanBenchmark:'PENDING',signing:'PENDING'});console.log(JSON.stringify({event:'browser validation',status:'PASS'}));
}finally{await browser.close();await quit(runtime,installation);if(installation!==root)await rm(installation,{recursive:true,force:true});}
