import assert from 'node:assert/strict';
import { origin, launch, ready, quit, persist } from './common.mjs';
const p=launch();const checks=[];try{await ready(p);
 const home=await fetch(origin+'/'),html=await home.text(),csp=home.headers.get('content-security-policy');assert.equal(home.status,200);assert.match(home.headers.get('content-type'),/text\/html/);assert.equal(home.headers.get('cache-control'),'no-store');assert.ok(!html.includes('@vite/client')&&!html.includes('/src/'));
 for(const directive of ["default-src 'self'","script-src 'self'","style-src 'self'","connect-src 'self'","media-src 'self' blob:","object-src 'none'","frame-ancestors 'none'"])assert.ok(csp.includes(directive));assert.ok(!csp.includes('unsafe-inline'));
 const assets=[...html.matchAll(/(?:src|href)="(\/assets\/[^" ]+)"/g)].map(m=>m[1]);assert.ok(assets.length>=2);for(const path of assets){const r=await fetch(origin+path);assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/immutable/);assert.match(r.headers.get('content-type'),path.endsWith('.css')?/text\/css/:/javascript/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');}
 for(const path of ['/study/read-aloud','/study/repeat-sentence','/study/write-from-dictation'])assert.equal((await fetch(origin+path)).status,200);
 for(const path of ['/api/unknown','/api/v1/health?x=1','/api/v1/transcribe/','/.local-runtime/model','/manifest/package.json','/native/node','/assets/../native/node','/assets/unknown.js','/assets/unknown.map']){const r=await fetch(origin+path);assert.equal(r.status,404);checks.push({path,status:'PASS'});}
 const health=await fetch(origin+'/api/v1/health');assert.equal(health.headers.get('cache-control'),'no-store');assert.equal(health.headers.get('x-content-type-options'),'nosniff');const b=await health.json();assert.equal(b.status,'ready');for(const forbidden of ['hostname','username','paths','hashes'])assert.ok(!(forbidden in b));
 await quit(p);const lines=p.output().trim().split('\n');for(const line of lines){const object=JSON.parse(line);assert.ok(Object.keys(object).every(k=>['event','origin'].includes(k)));}assert.equal(p.error(),'');
 await persist('linux-http.json',{status:'PASS',staticAssets:assets.length,productionHTML:'PASS',sameOrigin:'PASS',fingerprintedCacheAndMIME:'PASS',spaRoutes:'PASS',apiResourceIsolation:checks,responseHeaders:'PASS',strictCSPHeader:'PASS',structuredLauncherLogs:'PASS',privateRuntimeOutput:'discarded by launcher; no persisted log files',devClient:'absent'});console.log(JSON.stringify({event:'HTTP/static/log validation',status:'PASS'}));
}finally{await quit(p);}
